IBM/prompt-declaration-language

- .github/workflows/mkdocs-gh-pages.yml
> Publish the PDL schema on https://ibm.github.io/prompt-declaration-language/dist/pdl-schema.json

- README.md
I was working in the main README.md file to make it more concise and simple, to start faster and interact with the couple of main tools/features. 
The rest of the content continue to be accessible in the docs/README.
> Work in the Readme.

- README.md
- docs/README.md
- examples/cldk/cldk-assistant.pdl
- examples/fibonacci/fib.pdl
- src/pdl/pdl.py
Comments for Fibonacci (for #241 ).
Typo fixes including capitalization of trademarks.
> Comments for the Fibonacci example.  Typo fixes

- pdl-live-react/src/Context.ts
- pdl-live-react/src/view/transcript/Block.css
- pdl-live-react/src/view/transcript/BreadcrumbBar.css
- pdl-live-react/src/view/transcript/BreadcrumbBar.tsx
- pdl-live-react/src/view/transcript/BreadcrumbBarItem.tsx
- pdl-live-react/src/view/transcript/Def.tsx
- pdl-live-react/src/view/transcript/Defs.tsx
- pdl-live-react/src/view/transcript/InfoPopover.tsx
- pdl-live-react/src/view/transcript/Transcript.tsx
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
> fix: improve rendering of variable definitions

- pdl-live-react/src/view/transcript/BreadcrumbBar.css
> fix: reduce number of colors

- pdl-live-react/src/view/transcript/Def.tsx
In one place we were still using a Label UI.
> fix: variable definition drilldown ui inconsistency

- pdl-live-react/package.json
- pdl-live-react/src/DrawerContent.tsx
- pdl-live-react/src/Viewer.tsx
- pdl-live-react/src/ViewerTabs.tsx
- pdl-live-react/src/view/Preview.css
- pdl-live-react/src/view/Preview.tsx
- pdl-live-react/src/view/transcript/DefContent.css
- pdl-live-react/src/view/transcript/DefContent.tsx
- pdl-live-react/yarn.lock
via @patternfly/react-code-editor
> feat: switch to monaco-editor in react viewer

- pdl-live-react/src/view/transcript/BreadcrumbBar.css
- pdl-live-react/src/view/transcript/Transcript.css
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
problematic with z-index clicks and requires a global dom id for the click area. problemtic!
> fix: avoid use of patternfly Card isClickable

- pdl-live-react/src/Page.css
- pdl-live-react/src/Page.tsx
- pdl-live-react/src/view/transcript/FinalResult.css
- pdl-live-react/src/view/transcript/Output.tsx
- pdl-live-react/src/view/transcript/Transcript.css
- pdl-live-react/src/view/transcript/Transcript.tsx
> fix: further improvements to spacing and borders in react ui

- pdl-live-react/src/Viewer.tsx
- pdl-live-react/src/ViewerTabs.tsx
- pdl-live-react/src/helpers.ts
- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/Timeline.tsx
- pdl-live-react/src/view/timeline/TimelineBar.tsx
- pdl-live-react/src/view/timeline/TimelineRow.tsx
- pdl-live-react/src/view/timeline/model.ts
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
This still needs a fix to properly present the tree "skeleton". We don't yet recognize last-sibling.
> feat: Timeline view in react viewer

- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/TimelineBar.tsx
rounded corners, plus fix a react warning
> fix: small tweaks to timeline ui

- pdl-live-react/src/view/timeline/Timeline.tsx
- pdl-live-react/src/view/timeline/TimelineRow.tsx
- pdl-live-react/src/view/timeline/model.ts
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
This also fixes a potential bug in the timeline model computation for "forests", i.e. graphs with multiple roots.
> fix: minor refactorings and fixes to render better on smaller devices

- pdl-live-react/src/About.tsx
- pdl-live-react/src/Demo.tsx
- pdl-live-react/src/Page.tsx
- pdl-live-react/src/PageBreadcrumbs.tsx
- pdl-live-react/src/Uploader.tsx
- pdl-live-react/src/Welcome.tsx
after uploading, one is presented with raw json.
this also adds page breadcrumbs to Welcome and About, and does some code cleanup/refactoring around this.
> fix: react viewer Upload page regression

- pdl-live-react/src/view/Preview.tsx
- pdl-live-react/src/view/detail/DrawerContent.tsx
- pdl-live-react/src/view/detail/DrawerContentBody.tsx
- pdl-live-react/src/view/detail/RawTraceTabContent.tsx
- pdl-live-react/src/view/detail/SourceTabContent.tsx
- pdl-live-react/src/view/detail/kind/Code.tsx
This also incorporates a small bit of code cleanup to view/detail
> fix: reactor editor views should word wrap; detail editor views should show line numbers

- pdl-live-react/src/page/DemoNavItems.tsx
- pdl-live-react/src/page/MyTraces.ts
- pdl-live-react/src/page/MyTracesNavItems.tsx
- pdl-live-react/src/page/Sidebar.tsx
- pdl-live-react/src/page/Uploader.tsx
- pdl-live-react/src/routes/PdlRoutes.tsx
TODO: add a way to delete a prior trace
> feat: add My Traces to react ui

- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/TimelineBar.tsx
- pdl-live-react/src/view/timeline/TimelineRowKindCell.tsx
we already had click drilldown on the row label text
> fix: in react ui, enable timeline bar click drilldown

- pyproject.toml
https://github.com/BerriAI/litellm/issues/8081
> fix: avoid litellm 1.59.9 for now

- pdl-live-react/package.json
this helps with debugging:
```shell
npm run view <path-to-trace.json>
```
> feat: add `npm run view` helper script to react ui

- src/pdl/pdl_interpreter.py
Resolves #333
To test, run _examples/chatbot/chatbot.pdl_ and exit using control-C or control-D instead of "yes".
> Don't crash without log on keyboard exit

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
- pdl-live-react/src/main.tsx
- pdl-live-react/src/page/DemoNavItems.tsx
- pdl-live-react/src/page/MyTracesNavItems.tsx
- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/page/Sidebar.tsx
- pdl-live-react/src/page/Uploader.tsx
- pdl-live-react/src/routes/PdlRoutes.tsx
- pdl-live-react/src/title.ts
- pdl-live-react/src/view/dataflow/DataFlow.tsx
- pdl-live-react/src/view/detail/DrawerContent.tsx
- pdl-live-react/src/view/timeline/TimelineBar.tsx
- pdl-live-react/src/view/timeline/TimelineRowKindCell.tsx
- pdl-live-react/src/view/transcript/Def.tsx
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
- pdl-live-react/src/view/transcript/TranscriptItemDef.tsx
with react-router@7, react-router-dom is just a stub.
> chore: react-router-dom -> react-router

- pdl-live-react/src/page/Page.css
- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/page/PageBreadcrumbs.tsx
- pdl-live-react/src/page/Uploader.tsx
- pdl-live-react/src/page/ViewerTabs.tsx
- pdl-live-react/src/page/welcome/Links.tsx
- pdl-live-react/src/page/welcome/Welcome.tsx
- pdl-live-react/src/routes/PdlRoutes.tsx
- pdl-live-react/src/view/transcript/Transcript.tsx
this also includes some generalized cleanups
> feat: add Home breadcrumb to react ui

- pdl-live-react/src/page/welcome/Welcome.css
- pdl-live-react/src/page/welcome/Welcome.tsx
- pdl-live-react/src/routes/PdlRoutes.tsx
This also adds a max-width to the Welcome page.
> fix: in react ui, initial page may 404

- pdl-live-react/src/page/Demo.tsx
- pdl-live-react/src/page/Demos.tsx
- pdl-live-react/src/page/MyTracesPage.tsx
- pdl-live-react/src/page/PageBreadcrumbs.tsx
- pdl-live-react/src/page/welcome/Tiles.tsx
- pdl-live-react/src/page/welcome/Welcome.tsx
- pdl-live-react/src/routes/PdlRoutes.tsx
and make first breadcrumb clickable
> feat: add /Home/Demos and /Home/My Traces sections to react ui

- pdl-live-react/src/page/Viewer.tsx
- pdl-live-react/src/page/ViewerTabs.tsx
- pdl-live-react/src/view/masonry/Duration.css
- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/Masonry.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/MasonryTimelineCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/model.ts
- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/Timeline.tsx
- pdl-live-react/src/view/timeline/TimelineFromModel.tsx
- pdl-live-react/src/view/timeline/TimelineRow.tsx
- pdl-live-react/src/view/timeline/TimelineRowKindCell.tsx
> feat: in react ui, combine masonry and timeline views

- pdl-live-react/src/page/Viewer.tsx
- pdl-live-react/src/page/ViewerTabs.tsx
- pdl-live-react/src/view/breadcrumbs/BreadcrumbBarForBlockId.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
> feat: in react ui, limit max breadcrumbs shown

- pdl-live-react/src/page/Page.css
- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/page/Viewer.tsx
- pdl-live-react/src/view/breadcrumbs/BreadcrumbBarForBlockId.tsx
- pdl-live-react/src/view/masonry/MasonryTimelineCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarViewToggle.tsx
- pdl-live-react/src/view/masonry/View.ts
> feat: in react ui, switch from tabs to toolbar ui

- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/model.ts
- pdl-live-react/src/view/memory/Memory.tsx
- pdl-live-react/src/view/memory/Node.tsx
- pdl-live-react/src/view/memory/Topology.tsx
- pdl-live-react/src/view/memory/layout.ts
- pdl-live-react/src/view/memory/model.ts
(already used in masonry and timeline)
> fix: in react ui, have topology adopt block numbering scheme

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/commands/replay.rs
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarReplayButton.tsx
https://github.com/user-attachments/assets/b5005240-67d4-4462-9544-756404b03c6d
> feat: update react ui to present logs of Run/Replay

- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/timeline/Timeline.css
This also removes the gray background from the Timeline
> fix: in react ui, teal -> blue and increase size of Timeline text

- pdl-live-react/src/view/code/PreviewLight.css
- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/timeline/Timeline.css
also small fix to work around more safari rendering bugs with column-span: all
> fix: react ui dark theme tweaks

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
- pdl-live-react/src/view/Markdown.css
- pdl-live-react/src/view/Markdown.tsx
> feat: syntax highlight code in markdown blocks

- pdl-live-react/src/page/DarkModeToggle.tsx
- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/MasonryTileWrapper.tsx
This also refactors out a MasonryTileWrapper component.
> fix: add border around timeline in react ui

- pdl-live-react/src/page/DarkModeContext.ts
- pdl-live-react/src/page/DarkModeToggle.tsx
- pdl-live-react/src/page/Masthead.tsx
- pdl-live-react/src/page/Page.css
- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/page/PageBreadcrumbs.tsx
- pdl-live-react/src/page/welcome/Toolbar.tsx
- pdl-live-react/src/page/welcome/Welcome.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
> feat: remove masthead from react ui

- pdl-live-react/src/view/breadcrumbs/BreadcrumbBarForBlockId.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
> fix: in react ui, avoid 'Text.Step 3' and 'If.Step 1' in masonry summary

- pdl-live-react/src/view/Result.tsx
- pdl-live-react/src/view/detail/kind/Data.tsx
This also updates Code to use line wrapping.
> fix: Data block detail may double-yaml-stringify

- pdl-live-react/src/view/detail/kind/Model.tsx
> feat: initial support for showing structured model responses in detail ui

- pdl-live-react/src/view/detail/kind/Model.tsx
> fix: clean up presentation of 'citation' in structured model response

- .github/workflows/mkdocs-gh-pages.yml
- docs/viewer.md
- mkdocs.yml
TODO: how do we get the iframe to be full height? i've hard-coded a pixel height for now.
> doc: attempt 3 to get react viewer live on github pages

- pdl-live-react/src/main.tsx
- pdl-live-react/tests/basics.spec.test.ts
and nested page reloads work on hosted sites
> fix: switch ui to HashRouter so that /index.html

- examples/notebooks/pdl.ipynb
- src/pdl/pdl_notebook_ext.py
> Fix Jupyter extension to work with lazy PDL implementation

- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/tauri.conf.json
- pdl-live-react/src/view/masonry/Masonry.tsx
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/Tile.ts
- pdl-live-react/src/view/masonry/model.ts
TODOs:
- figure out how to align the timestamps of all children subtrees that follow the spliced-in new subtree. This PR only updates the timestamps of the new subtree. This is needed so that the Timeline view makes sense: if the new subtree is faster or slower, we need to offset all following subtrees to compensate for this change.
https://github.com/user-attachments/assets/8145f576-a691-4016-bf5a-f8da22b4c764
> feat: ui Reload button in LLM block tiles

- src/pdl/pdl_notebook_ext.py
> Expose model default parameters to Jupyter interpreter

- pdl-live-react/src/view/masonry/Duration.tsx
> fix: work around for locale issues on linux

- pdl-live-react/src-tauri/src/cli/run.rs
This may solve a problem on windows with the `--data` argument and quoting. It also avoids a powershell/sh/bash choice.
> fix: in ui Run, avoid subshell execution

- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarReplayButton.tsx
- Runner is promise-based rather than callback-based
- ToolbarReplayButton doesn't need to manage "is replaying" state
- have ToolbarReplayButton show as yellow when running
> refactor: first stage of ui Run modal code cleanup

- pdl-live-react/src/view/masonry/RunMenu.tsx
> feat: add some placeholder menu items for alternate run modes in ui

- pdl-live-react/src-tauri/src/cli/setup.rs
Learning Rust on the job here...
> fix: if ui `pdl run` subprocess fails, panic ensues

- .gitignore
- examples/gsm8k/README.md
- examples/gsm8k/gsm8.pdl
(Creating as a **draft** because @mandel has changes for improving parallelism we still need to deliver).
> Grade School Math example

- pdl-live-react/src/pdl_ast.d.ts
- src/pdl/pdl-schema.json
- src/pdl/pdl_ast.py
For #678
Adds more detail and a few examples to our API documentation.
> Docstrings and examples for PDL concepts

- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/RunMenu.tsx
- pdl-live-react/src/view/masonry/Stability.css
Speed things up a bit for now. Also, this improves rendering of the tile footer -- use Flex rather than Grid.
> fix: run fewer experiments for ui stability analysis

- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/Stability.css
> fix: improve layout of stability popovers

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
This takes us off my fork/branch and on to a main line release.
> chore(deps): bump to tauri-pty@0.1.0

- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/interpreter/mod.rs
- pdl-live-react/src-tauri/src/interpreter/pip.rs
- pdl-live-react/src-tauri/src/interpreter/pull.rs
This also refactors the pip_install_if_needed() logic out of the run module and into the pull module.
> fix: only attempt ollama pull if model is not already local

- examples/tools/calc.pdl
Added comment to example per @esnible's request
> Added comment for example

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
Also removes unused @types dep
> chore: move from branch to npm release of tauri-pty

- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/interpreter/ast.rs
- pdl-live-react/src-tauri/src/interpreter/mod.rs
> refactor: move rust ast type defs into separate module

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
This also improves error handling to avoid the unwrap/panic paths.
> feat: update rust python support to pull in python stdlib

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/extract.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
And start populating the timing info (incomplete).
> refactor: refactor rust ast to place metadata in common struct

- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
more work is needed (e.g. model needs to be an Expr), but this is progress...
> fix: improve deserialization of python-generated model block traces

- pdl-live-react/package-lock.json
- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/src/gui.rs
And leverage the new prevent overflow feature of tauri.
> chore: bump tauri and npm dependencies

- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
- pdl-live-react/src-tauri/tests/cli/jsonl-parser.pdl
The program may not run 100% yet, but it parses now.
> fix: rust ast support for gsm8k, including jsonl parser

- pdl-live-react/demos/demo1.pdl
- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
- pdl-live-react/src-tauri/tests/cli/code-python.pdl
We need to send a system prompt to some models. Plus add some stubs for pydantic for python tool execution.
This also includes nascent support for openai-rs (not fully funcitonal yet).
> feat: improve support for tool calling in ollama-rs

- examples/rag/rag_library1.pdl
Resolves https://github.com/IBM/prompt-declaration-language/issues/928
> Fix rag example by fully qualifying import
