IBM/prompt-declaration-language

- src/pdl/pdl_interpreter.py
A minor change to include the model name when reporting model failures.
If the failure is due to network connectivity, the output now includes that.  Where before we logged 
```
basic.pdl:4 - Error during model call: ConnectError('[Errno 61] Connection refused')
```
we now show
```
basic.pdl:4 - model 'ollama/granite-code:8b' encountered ConnectError('[Errno 61] Connection refused') trying to POST against http://localhost:11434/api/generate
```
> Show the model name, and request info if possible, on error

- README.md
- docs/README.md
- docs/tutorial.md
- examples/callback/repair_prompt.pdl
- examples/chatbot/chatbot.pdl
- examples/code/code-eval.pdl
- examples/code/code-json.pdl
- examples/code/code.pdl
- examples/fibonacci/fib.pdl
- examples/granite/README.md
- examples/granite/multi_round_chat.pdl
- examples/granite/single_round_chat.pdl
- examples/hello/hello-def-use.pdl
- examples/hello/hello-model-chaining.pdl
- examples/hello/hello-model-input.pdl
- examples/hello/hello-parser-regex.pdl
For #241
First step at adding more comments to document examples.
> Add comments to examples to make them more obvious

- pdl-live-react/src/title.ts
- pdl-live-react/src/view/transcript/PrettyKind.tsx
- pdl-live-react/src/view/transcript/QAV.css
- pdl-live-react/src/view/transcript/QAV.tsx
- pdl-live-react/tests/basics.spec.test.ts
Also improves test coverage of the various pages.
Also fixes a bug in `useDynamicTitle()` that resulted in failure on `/`
> fix: pdl-live-react improve ui of top-level q&a

- pdl-live-react/src/App.tsx
- pdl-live-react/src/Demo.tsx
- pdl-live-react/src/Page.tsx
- pdl-live-react/src/Uploader.tsx
- pdl-live-react/src/Viewer.tsx
These got lost in a recent refactoring
> fix: restore top-level breadcrumbs

- pdl-live-react/src/view/transcript/Array.tsx
- pdl-live-react/src/view/transcript/Block.tsx
- pdl-live-react/src/view/transcript/Blocks.tsx
- pdl-live-react/src/view/transcript/BlocksConjoin.tsx
- pdl-live-react/src/view/transcript/DefContent.tsx
- pdl-live-react/src/view/transcript/LastOf.tsx
- pdl-live-react/src/view/transcript/LoopTrace.tsx
- pdl-live-react/src/view/transcript/Object.tsx
- pdl-live-react/src/view/transcript/Query.tsx
- pdl-live-react/src/view/transcript/Text.tsx
- pdl-live-react/src/view/transcript/Transcript.tsx
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
we had been intermixing properly nested react components with random functions that created components. this was confusing vite's HMR (hot method refresh), though didn't lead to any functional defects.
> fix: clean up react viewer to avoid use of non-components

- src/pdl/pdl.py
- src/pdl/pdl_ast.py
- src/pdl/pdl_interpreter.py
- src/pdl/pdl_llms.py
- src/pdl/pdl_utils.py
- tests/test_defaults.py
Resolves #200
Introduces configuration for model parameter defaults.
Model parameter defaults can be changed with the `--data-file` option.  For example, `pdl --data-file model_defaults.yaml hello4.pdl `.
[model_defaults.yaml.txt](https://github.com/user-attachments/files/18459576/model_defaults.yaml.txt)
> Config options for model default parameters

- pdl-live-react/src/Context.ts
- pdl-live-react/src/Viewer.tsx
- pdl-live-react/src/view/Code.tsx
- pdl-live-react/src/view/Preview.tsx
- pdl-live-react/src/view/transcript/Block.tsx
- pdl-live-react/src/view/transcript/CodeGroup.tsx
- pdl-live-react/src/view/transcript/DefContent.tsx
- pdl-live-react/src/view/transcript/FinalResult.tsx
- pdl-live-react/src/view/transcript/Function.tsx
- pdl-live-react/src/view/transcript/Result.tsx
- pdl-live-react/src/view/transcript/ResultOrCode.tsx
- pdl-live-react/src/view/transcript/Transcript.tsx
- pdl-live-react/src/view/transcript/TranscriptItem.tsx
this simplifies the viewer code, as we no longer need to pass down the darkMode state. it arguably also looks better, at least more conventional -- code is dark.
> fix: code preview should always be dark in react viewer

- pdl-live-react/src/view/Preview.css
- pdl-live-react/src/view/Preview.tsx
> feat: enable copy button, etc. buttons for CodeEditor in react ui

- pdl-live-react/src/Sidebar.tsx
This also fixes routing so as to preserve selected tab when switching between demos.
> fix: Sidebar does not highlight demos

- pyproject.toml
- src/pdl/pdl_ast.py
As of LiteLLM 1.52.1, model prefix `watsonx/` points to the `/chat` endpoint. See change [here](https://github.com/BerriAI/litellm/commit/5c5527074045aa1e0ed90f2aaf02f38402e758e9#diff-1f5c142ba9c5f1b4e12d2bb8bf20fc82e84fb33e02846c9cd99fd281e4a4a800R2623). This endpoint has several differences in accepted [parameters](https://cloud.ibm.com/apidocs/watsonx-ai#text-chat-request), and more sane defaults. It supports `json_object` as a `response_format`, and the endpoint supports tool calling (future work for PDL). Rather than handle different LiteLLM dependency versions pointing to different APIs, this PR also bumps the minimum LiteLLM version needed. One thing to note, `set_default_granite_model_parameters` is only called for granite models of course. This means that using Granite, the …
> Set default params for Watsonx chat & text models

- pdl-live-react/src/view/detail/DrawerContentBody.tsx
When not showing the details on initial page load, this saves about 50-100ms of page load time.
> fix: in react ui, lazily load detail components

- pdl-live-react/src/page/Viewer.tsx
no sense in loading all of the UI components to display the initial tab. but still avoid re-mounting tab content when switching back and forth
> fix: in react ui, implement mount-on-enter behavior for tabs

- src/pdl/pdl_interpreter.py
Apply the default parameters later, after processing.
This is a follow-up to https://github.com/IBM/prompt-declaration-language/pull/266 based on Slack comments about the program
```PDL
defs:
params:
data: { temperature: 1 }
model: replicate/ibm-granite/granite-3.0-8b-instruct
parameters: ${ params }
input: Hello
```
> Apply defaults only after parameter processing

- .github/workflows/pdl-live-react-tests.yml
This slipped through the cracks of #339
> test: update github actions for react ui to use npm not yarn

- pdl-live-react/package.json
- pdl-live-react/src-tauri/src/lib.rs
- pdl-live-react/src-tauri/tauri.conf.json
```shell
PDL run <source.pdl>
```
> feat: embed PDL interpreter into react (tauri) app builds

- pdl-live-react/src/page/PageBreadcrumbs.tsx
- pdl-live-react/src/page/Sidebar.tsx
This is related to #361, which only fixed half of the problem.
> fix: in react ui, sidebar may re-close when navigating

- pdl-live-react/src/view/timeline/Timeline.tsx
- pdl-live-react/src/view/timeline/TimelineRow.tsx
This can happen when the trace prematurely exits, leaving `end_nanos: 0` for some blocks
> fix: react ui Timeline view may show large negative durations

- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/Masonry.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/MasonryTimelineCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarAsToggle.tsx
- pdl-live-react/src/view/masonry/ToolbarSMLToggle.tsx
also preserve masonry spacing and grid-vs-list settings across sessions
> feat: in react ui, allow user to choose masonry spacing

- tests/test_hello.py
We already support this (since yaml can embed json), but it seems worthwhile having an explicit test for this.
> test: add test coverage for passing a json-formatted pdl program

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
- pdl-live-react/src/view/breadcrumbs/BreadcrumbBarForBlockId.tsx
- pdl-live-react/src/view/masonry/Masonry.tsx
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/memory/Memory.tsx
- pdl-live-react/src/view/memory/Node.tsx
- pdl-live-react/src/view/memory/Topology.tsx
- pdl-live-react/src/view/memory/components.ts
- pdl-live-react/src/view/memory/layout.ts
- pdl-live-react/src/view/memory/model.ts
This still needs some iteration. For one, if we have no dataflow info, the view shows up as blank.
> feat: in react ui, restore topology ui

- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/memory/Node.tsx
- pdl-live-react/src/view/timeline/Timeline.css
The previous blue overlapped colors with the blue "variable" breadcrumbs.
> fix: in react ui, show code blocks in purple

- pdl-live-react/src/view/memory/Topology.css
- pdl-live-react/src/view/memory/Topology.tsx
So that edges can be seen underneath the labels
> fix: in react ui, topology labels should be see-through

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/commands/mod.rs
- pdl-live-react/src-tauri/src/commands/replay.rs
- pdl-live-react/src-tauri/src/lib.rs
- pdl-live-react/src/page/Demo.tsx
- pdl-live-react/src/page/Local.tsx
- pdl-live-react/src/page/MyTrace.tsx
- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarReplayButton.tsx
- pdl-live-react/src/view/masonry/ToolbarShowSourceButton.tsx
Limitations:
- programs with user input will probably hang
- for now, only re-running the entire program is supported
- while re-running, the only visual feedback is a spinner inside the Run button
TODOs:
- we should present a timestamp somewhere of when the trace was last updated
- we could stream console output somehow to the UI
- we could also stream ollama server output to the UI
> feat: in react UI, add Run button to support re-running program

- Formula/README.md
- Formula/pdl.rb
- pdl-live-react/package.json
- pdl-live-react/src-tauri/tauri.conf.json
- pdl-live-react/src/view/masonry/Toolbar.tsx
This also (for now) disables the Run button in the react ui, and disables packaging of the interpreter. Doing so currently results in notarization failures (macos) due to the interpreter resources not being signed. So we'll need to figure thatout before we can re-enable Run.
> feat: add homebrew formula

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/commands/replay.rs
- pdl-live-react/src-tauri/tauri.conf.json
- pdl-live-react/src/view/masonry/Toolbar.tsx
I had to disable this temporarily as the prior implementation was blocking macos notarization. With this update, instead of inlining an entire venv as a tauri resource, we inline only the requirements.txt.
> feat: in react ui re-enable Replay/Run button and functionality

- pdl-live-react/src/view/memory/Topology.tsx
This seems to be a bug in `@patternfly/react-topology`... This introduces a workaround, by asking the topology controller to `setFitToScreenOnLayout(true)`. This introduces a different quirk, in which the topology renders (off-viewport) and then immediately shifts and resizes. Sigh. I don't know of a way (yet) to ask the topology logic to render off screen (to get its size) and only then render on-screen. But this quirk seems preferably to having the topology render mostly off-viewport.
> fix: in react ui, topology is often partially off-viewport

- pdl-live-react/src/view/masonry/Duration.css
- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/timeline/Timeline.css
This also updates S display mode to show only the tree, not the timeline bars or duration.
> fix: react ui Timeline tree spine vertical gap

- pdl-live-react/src/view/Result.tsx
- pdl-live-react/src/view/Value.tsx
- pdl-live-react/src/view/code/Code.tsx
- pdl-live-react/src/view/code/PreviewLight.tsx
- pdl-live-react/src/view/detail/RawTraceTabContent.tsx
- pdl-live-react/src/view/detail/SourceTabContent.tsx
- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- raised panel to better offset content inside tile
- improved inner scrolling, with the scrollbars hugging the perimeter of the tile
- some related improvements to display of markdown-like content inside tiles
> fix: in react ui, improve display of masonry tiles via use of panel

- pdl-live-react/src/page/Sidebar.tsx
The drawer content will be specific to a trace...
> fix: in react ui, close drawer when switching to a different trace

- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/model.ts
This also improves the line-height rendering.
> fix: in react ui, timeline tree sometimes has dangling last child spines

- pdl-live-react/src/view/timeline/Timeline.css
This also increases bar min-width from 1px to 0.25em.
> fix: react ui timeline bars need a bit of vertical separation

- pdl-live-react/src/page/Page.tsx
- pdl-live-react/src/page/PageBreadcrumbs.tsx
- pdl-live-react/src/page/welcome/Welcome.tsx
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
This also fixes the breadcrumb for the welcome page to avoid Home > Welcome. Now it will be just Home.
> fix: improve padding/spacing in react ui Welcome page

- pdl-live-react/src/helpers.ts
- pdl-live-react/src/view/masonry/model.ts
- pdl-live-react/src/view/timeline/model.ts
We now "unfurl" the defs. Previously in this screenshot, defs -> LLM would show only as Empty.
> fix: improve rendering of empty blocks in react ui

- pdl-live-react/src/view/masonry/Masonry.css
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/timeline/Timeline.css
- pdl-live-react/src/view/timeline/TimelineRowKindCell.tsx
Hmm... experimenting here... Full-width timelines don't render particular well for the use cases we have so far. They render as just a bunch of very wide awkward bars.
This also updates the timeline to use the (1) circled number UI from the masonry tiles.
> fix: in react ui, try going back to timeline as part of the masonry grid

- pdl-live-react/src/view/Markdown.css
- pdl-live-react/src/view/Value.tsx
- pdl-live-react/src/view/detail/ContextTabContent.tsx
This also adds placeholder text for context messages with no defsite.
> fix: in ui, Context tab can show raw json strings

- .github/workflows/mkdocs-gh-pages.yml
- pdl-live-react/vite.config.ts
under `/prompt-declaration-language/viewer`
this does not update the mkdocs pages themselves to reference the viewer. first, let's get the viewer onto github pages...
Closes #446
> doc: update GitHub Pages builder to build and serve react ui

- README.md
For #448
Using `stop_sequences` with Ollama causes Ollama to log a warning about an unknown parameter.
> Use stop: instead of stop_sequences

- pdl-live-react/src/view/code/PreviewLight.tsx
- pdl-live-react/src/view/detail/DrawerContent.css
- pdl-live-react/src/view/detail/DrawerContent.tsx
- pdl-live-react/src/view/detail/RawTraceTabContent.tsx
- pdl-live-react/src/view/detail/SourceTabContent.tsx
Previously, the whole detail panel would scroll, including header and tabs. With this, only the tab content scrolls.
> fix: improve scrolling ui in detail (sidecar) view

- pdl-live-react/src/view/masonry/Masonry.tsx
Due to a bug that lead to two masonry tiles having the same react `key`, switching e.g. from Chatbot to Code Explanation back to Chatbot would lead to blocks bleeding between the second and third...
> fix: switching between ui demos can lead to funky masonry tiles

- src/pdl/pdl_notebook_ext.py
Resolves #561
This handles the case where the user's cell does not include `--reset-context`.
Or Jupyter extension uses the `@needs_local_scope` decorator on our Jupyter cell magic function.  When our function is called our local scope object has non-lazy types.  (That surprised me, because the types seem lazy when we exit the previous cell magic.). This PR ensures a lazy context.
> Ensure lazy context

- pdl-live-react/src/page/PageBreadcrumbDropdownItem.tsx
- pdl-live-react/src/view/detail/DrawerContent.tsx
- pdl-live-react/src/view/detail/DrawerContentBody.tsx
- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarShowSourceButton.tsx
- pdl-live-react/src/view/masonry/model.ts
We have been showing program output in the masonry view and program source under the top-level toolbar Show Source button. This consolidates these: we aleady have the capability to show source+output of any block in the drawer/detail view.
So: remove output from masonry, and update Show Source button so that, rather than special case a "source" object type, just show the root block detail.
> feat: consolidate Show Source + Output of Program

- .github/workflows/release-ui.yml
And also to build for arm and x86 linux.
> fix: adjust release-ui workflow to use repo tag and release naming conventions

- docs/telemetry.md
The Telemetry doc specifies the wrong endpoint for Jaeger Open Telemetry.
cc @jgchn
> Incorrect endpoint in Telemetry doc

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/tauri.conf.json
We want the package (and macos app bundle) to be named PDL, but we want the actual executable (used on the command line) to be pdl.
> fix: tweak ui app config so as to produce a lower-case 'pdl' executable

- src/pdl/pdl_granite_io.py
- src/pdl/pdl_interpreter.py
- src/pdl/pdl_llms.py
- src/pdl/pdl_schema_validator.py
- lazy load litellm
- granite_io startup optimizations by pulling the class into its own file
- lazy load jsonschema
On MacOS this shaves `pdl` (with no arguments) from 1.1s down to 500ms (350ms with the second commit; 330ms with third)
On Windows (Parallels VM on MacOS host), this shaves 6.25s down to 2.1s (1.5s with the second commit; 1.3s with third commit)
@esnible including you because this adjusts the OTEL bits. could you test? thanks
ref https://github.com/BerriAI/litellm/issues/7605
> chore: improve startup time of pdl python

- pdl-live-react/src/view/masonry/MasonryTile.tsx
- pdl-live-react/src/view/masonry/RunMenu.tsx
No added functionality here, but paving the way for alternate run actions besides Run Once (what we had before as the default behavior of the run icon button).
> feat: switch ui tile run menu to split action dropdown

- pdl-live-react/package-lock.json
- pdl-live-react/package.json
- pdl-live-react/vite.config.ts
This seems to be caused by vite-plugin-html's use of `consola.wrapConsole()`, and it seems to treat `console.error()` as still worthy of printing an 'ERROR' prefix to the console. The underlying culprit is `vite-plugin-checker`, which doesn't seem to be useful at this point, anyway. So this change removes use of `vite-plugin-checker`.
> fix: ui 'npm run dev' emits spurious empty 'ERROR' output on console

- pdl-live-react/src/view/timeline/model.ts
- src/pdl/pdl_dumper.py
- src/pdl/pdl_llms.py
This at least fixes the block timestamps for async model calls. i don’t think it’s possible to do this generally (at least with my understanding of python futures), because the pdl_lazy logic obscures the original asyncio.Future… but this future is available at the point of fire for the async model calls… so i’ve fixed that part.
It’s imperfect. As you can see in the screenshot, an outer Text block… doesn’t know that there are Futures under the hood. but still this seems like an improvement over what we had. and that might be something we can patch over in the UI.
This includes said patch to the UI (see src/view/timeline/model.ts, the comment that references #683). The screenshot would be the UI without this UI patch.
> fix: correct end_nanos accounting for async model calls

- src/pdl/pdl_lazy.py
When running `pdl --data '{"pdl_context": somethingsomething}' prog.pdl`, if prog.pdl is just a model block, it works. If prog.pdl is a text block wrapped around that model block, it fails with
```
File "/Users/nickm/git/prompt-declaration-language/src/pdl/pdl_interpreter.py", line 438, in process_block_body
result, background, scope, trace = process_call_model(
^^^^^^^^^^^^^^^^^^^
File "/Users/nickm/git/prompt-declaration-language/src/pdl/pdl_interpreter.py", line 1247, in process_call_model
model_input = scope["pdl_context"]  # pyright: ignore
~~~~~^^^^^^^^^^^^^^^
File "/Users/nickm/git/prompt-declaration-language/src/pdl/pdl_lazy.py", line 119, in __getitem__
result = v.result()
^^^^^^^^^^
File "/Users/nickm/git/prompt-declaration-language/src/pdl/pdl_lazy.py", line 211, in result
v1 = …
```
> fix: pdl_lazy errors out when provided with --data on command line

- pdl-live-react/src/view/masonry/Masonry.tsx
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/masonry/Toolbar.tsx
- pdl-live-react/src/view/masonry/ToolbarPaginator.tsx
> feat: add Pagination to UI

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/interpreter/load.rs
This also fixes a bug in the model puller to avoid pulling the same model more than once.
> feat: update auto-pull logic to run in parallel with pip install

- .github/workflows/tauri-cli.yml
This should now cover all of the UI demos.
> test: extend tauri cli github actions tests

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/interpreter/mod.rs
- pdl-live-react/src-tauri/src/interpreter/pip.rs
- pdl-live-react/src-tauri/src/interpreter/shasum.rs
Previously, we had been using a fixed `interpreter-python` as the dirname for the cached venv.  With this change, we sha256sum the requirements.txt and use that as the dirname (and cache key).
This should pave the way to caching other venvs, such as for program code blocks.
> feat: use shasum as cache key for venv

- pdl-live-react/src-tauri/src/interpreter/extract.rs
- pdl-live-react/src-tauri/src/interpreter/mod.rs
- pdl-live-react/src-tauri/src/interpreter/pull.rs
this should let us have an `extract_requirements()` to help with managing venvs of code blocks
> refactor: extract a common `extract_values()` in the rust model pulling logic

- pdl-live-react/src/page/PageBreadcrumbDropdownItem.tsx
See #478 for the related (prior) fix in the Sidebar component.
> fix: in ui, close drawer when switching to a different trace from breadcrumb

- pdl-live-react/src-tauri/src/interpreter/pip.rs
- pdl-live-react/src-tauri/src/interpreter/shasum.rs
use venv/ dir and use base64 url encoder to avoid / in hash dir name
> fix: adjust rust cli venv cache path

- pdl-live-react/src/view/detail/DrawerContent.css
- pdl-live-react/src/view/detail/DrawerContent.tsx
Previously, the detail drawer scrollbars were placed within the padded content. With this change, the scrollbars are flush to the boundaries of the detail drawer.
> fix: improve padding of detail drawer

- pdl-live-react/src/view/code/Code.tsx
This also cleans up that logic to avoid the explicit `delete` calls.
> fix: ui Source tab shows `pdl__usage` field

- pdl-live-react/src/view/timeline/model.ts
If we find block_i such that block_(i+1) is a model block whose final input message was defined by block_i, then we can skip showing block_i. No sense in repeating ourselves...
> feat: ui does not need to repeat model input

- pdl-live-react/src/view/masonry/model.ts
- pdl-live-react/src/view/timeline/model.ts
This also eliminates "<newline>" only blocks in the masonry ui.
> fix: refinements to ui avoiding repeating model inputs

- pdl-live-react/requirements.txt
- pdl-live-react/src-tauri/src/commands/replay_prep.rs
- pdl-live-react/src/view/masonry/MasonryCombo.tsx
- pdl-live-react/src/view/term/RunTerminal.tsx
We had been pointing to a remote git branch. To fix this required passing through `cwd` to the pty spawn, because it defaults to using the user's home directory. If we want to use a relative path to the interpreter in our requirements.txt, we need to inherit cwd.
> fix: update ui to support pulling interpreter from local dir

- src/pdl/pdl_interpreter.py
> Error during 'ollama/granite3.2:2b' model call: TypeError("litellm.main.completion() got multiple values for keyword argument 'stream'")
> fix: interpreter fails when passed parameters with null/None values

- .github/workflows/tauri-cli.yml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/compile/mod.rs
- pdl-live-react/src-tauri/src/lib.rs
- pdl-live-react/src-tauri/tauri.conf.json
This also improves error handling in the rust code.
Very primitive support at the moment. No tool calling (yet).
```shell
pdl compile beeai input.json -o output.pdl
```
Where, for now, `input.json` is generated by hand from a bee program using this monkey patch: 
```python
def dry_run(inputs):
class DryRunAnswer:
def __init__(self):
import jsonpickle
self.final_answer = jsonpickle.encode({"inputs": inputs, "workflow": workflow}, make_refs=False)
class DryRunResult:
result = DryRunAnswer()
class DryRun:
def on(self,a,b):
return self
async def _run_tasks(self):
return DryRunResult()
def __await__(self):
return self._run_tasks().__await__()
class DryRunContext:
@staticmethod
def enter():
return DryRun()
return DryRunContext.enter()
workflow.run = dry_run
```
and with patches to …
> feat: compile bee to pdl

- pyproject.toml
Error with examples/rag.py pre-commit run:
```
examples/rag/rag.py:108:21 - error: Cannot access attribute "data" for class "Coroutine[Any, Any, EmbeddingResponse]"
```
https://github.com/BerriAI/litellm/issues/9526
> fix: skip litellm 1.63.14

- pyproject.toml
This is until we can pick up a litellm fix.
https://github.com/BerriAI/litellm/issues/9424
> fix: pin openai==1.61.0 pip due to breaking change on their side

- pdl-live-react/beeai-requirements.txt
- pdl-live-react/requirements.txt
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/interpreter/mod.rs
- pdl-live-react/src-tauri/src/interpreter/pip.rs
- pdl-live-react/src-tauri/src/interpreter/requirements.rs
- pdl-live-react/src-tauri/src/interpreter/shasum.rs
- pdl-live-react/src-tauri/tauri.conf.json
This is a step towards rendering the main logic agnostic of Tauri -- so that it can run in plain CLIs and other (non-tauri) applications.
> fix: avoid use of tauri `resources` to inject requirements.txt data

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/interpreter/pip.rs
We can use the `dirs` crate. This is a step towards rendering the main logic agnostic of Tauri -- so that it can run in plain CLIs and other (non-tauri) applications.
> fix: avoid use of tauri cache dir logic

- pdl-live-react/src-tauri/src/cli/run.rs
- pdl-live-react/src-tauri/src/cli/setup.rs
- pdl-live-react/src-tauri/src/interpreter/pull.rs
- pdl-live-react/src-tauri/src/interpreter/requirements.rs
- pdl-live-react/src-tauri/src/lib.rs
- pdl-live-react/src/page/Local.tsx
- pdl-live-react/src/view/term/RunTerminal.tsx
Also some rust code cleanups around error handling and arg parsing. As part of these changes, a bit more disentangling from Tauri (ArgData is no longer in run.rs).
> fix: pdl view trace.json fixes

- src/pdl/pdl_schema_error_analyzer.py
When the PDL doesn't match the schema, the error analysis fails as it attempts to retrieve the field names without verifying that `"properties"` key exists in `ref_type`.
This change returns an empty `dict` if `properties` key doesn't exist in `ref_type` to allow the error analysis to complete successfully.
Fixes: #850
```yaml
description: Vision model example
text:
- model: openai/gpt-4o-mini
input:
array:
- role: user
content:
- type: text
text: "What's in this image?"
- type: image_url
image_url:
url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
parameters:
max_tokens: 500
temperature: 0.7
```
```text
['from-string:8 - [{\'type\': \'text\', \'text\': "What\'s in this …
```
> fix: Bug in pdl_schema_error_analyzer that raises exception during analysis

- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/tests/cli/read-stdin.pdl
> feat: add support for multiline reads to rust interpreter

- .github/workflows/rust-interpreter.yml
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
This will force a test of the built-in rust-based pull logic.
> test: update github action rust interpreter test to remove ollama pull

- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
This also updates the interpreter so that we get a compile time error if the match-over-block type is not exhaustive.
> fix: add kind tags to rust ast blocks

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/pdl/extract.rs
- pdl-live-react/src-tauri/src/pdl/pull.rs
1. extract was not traversing completely, thus missing some model references 
2. ollama pull itself (the CLI) may double/triple fetch if concurrent ollama pulls are launched. this PR introduces a file lock to avoid this. in github actions, we were running out of disk space due to this issue.
> fix: rust pull logic may not always pull

- .github/workflows/tauri-cli.yml
This also removes the beeai compiler test in that workflow, as we now cover that in the core rust interpreter tests.
> test: tauri github actions test should apt install the deb

- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/extract.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
Rather than duplicating this "metadata" logic -- the stuff common to all non-literal blocks. This just starts the migration. The main trick is to use the serde `flatten` capability, so that we can maintain a separate Metadata struct in Rust, but have it flattened into the enclosing object for serde.
> fix: begin phasing in Metadata (common defs, etc. attrs) into rust AST

- pdl-live-react/src-tauri/src/cli.rs
- pdl-live-react/src-tauri/src/compile/beeai.rs
- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
This also adds initial scaffolding for timing, and adds a ModelBlock and ArrayBlockBuilder.
> refactor: add metadata attr to remaining rust block asts

- pdl-live-react/src-tauri/src/pdl/interpreter.rs
This only covers the run_model code path, but it's a start.
> fix: rust interpreter was not handling pdl__context for re-runs of traces

- .github/workflows/rust-interpreter.yml
- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
- pdl-live-react/src-tauri/tests/cli/code-python.pdl
a bit of a hack at the moment to find (on linux/mac) the site-packages subdir when running in a virtual env. it should work on python 3.12. otherwise, one needs to set `PYTHONPATH` or `PDLPYTHONPATH`.
> fix: improve support for rust interpreter python imports from venv

- pdl-live-react/src-tauri/Cargo.lock
- pdl-live-react/src-tauri/Cargo.toml
- pdl-live-react/src-tauri/src/pdl/ast.rs
- pdl-live-react/src-tauri/src/pdl/interpreter.rs
- pdl-live-react/src-tauri/src/pdl/interpreter_tests.rs
- pdl-live-react/src-tauri/tests/cli/regex-findall.pdl
> feat: some regex parser support for rust interpreter

- src/pdl/__init__.py
- tests/test_lib_version.py
It wasn't set previously because importlib searches for the distribution name and not the module's top-level name. Fallbacks are in place to revert to searching for 'pdl', and if that fails, it fallsback to the hardcoded version in _version.py
The value of `pdl.__version__` shows "0.6.0" in my Python package which depends on `prompt-declaration-language` library.
The unit-test added with this change doesn't pick up the public version. It returned `0.1.dev1051+ga202a3d` as the version, which is different from the one hardcoded in `_version.py` file;  `0.1.dev1060+g3e3e31c.d20250408`.
To avoid test failures, for now and in the near future, the checks I added were to make sure that `pdl.__version__` was not `None`, and that it started with `"0.1.dev"`.
```python
from packaging.version import …
```
> Fixed the bug where pdl.__version__ was not set

- pdl-live-react/src/pdl_ast.d.ts
- src/pdl/pdl-schema.json
- src/pdl/pdl_ast.py
- src/pdl/pdl_dumper.py
- src/pdl/pdl_interpreter.py
- tests/test_retry.py
Signed-off-by: hirokuni-kitahara <hirokuni.kitahara1@ibm.com>
This PR is based on the issue https://github.com/IBM/prompt-declaration-language/issues/823 and it adds two new fields `retry` and `trace_error_on_retry` to the `block` class.
`retry` is an integer value which indicates the number of retry when some errors happen within the block. retry is enabled only when the value is specified and positive.
`trace_error_on_retry` is a boolean value whether to add error information to the trace. This defaults to None (=False), but when it is set to True, errors during retry are added to the trace. This is useful for multiple trials with `model` block to leverage self-reflection behavior of LLM.
```
The following is the original PR description before discussion in the comments.
---
This PR is …
```
> Add a new retry feature to `block`

- src/pdl/pdl_ast.py
This is helpful when communicating with a non-standard endpoint, e.g. one running locally. for local execution, it would normally be `OPENAI_API_BASE=http://localhost:8000/v1`
> fix: unable to set OPENAI_API_BASE for litellm
